### ISSUE TITLE
Logo Design For Concards Go

### ISSUE THREAD

**Issue by zularizal** [alanxoc3/concards-go#11]
Hi @chrisbdaemon , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by chrisbdaemon** [comment]
@alanxoc3 would be the one to talk to about this.

**Comment by alanxoc3** [comment]
Yeah, do it! I'll take it. I'm very proud of this project and use it for myself all the time. Maybe a logo will motivate me to document it more.

**Comment by zularizal** [comment]
Hi, sorry late reply. This is the logo design for your project. What do you think?

If something wants to be changed, let me know

![bitmap](https://user-images.githubusercontent.com/38547278/45489626-ef21aa00-b78e-11e8-90ff-3aed744cabac.png)

**Comment by alanxoc3** [comment]
No prob, they all look pretty good, but I like 3 the most!

**Comment by zularizal** [comment]
I have uploaded the logo to the drive in several vector and other formats.

https://drive.google.com/open?id=1IfKzOHsCRGaha1XnEdVT3KI2zuRGdHYF

And also I have sent a pull request to you #12
