### ISSUE TITLE
Implement terminal UI

### ISSUE THREAD

**Issue by chrisbdaemon** [alanxoc3/concards-go#6]
**Commands**
- [ ] Quit
- [ ] Stats
- [ ] Clear screen
- [ ] Write
- [ ] Help

**Modes**
- [x] Review
- [ ] Memorize
- [x] Done

**Other**
- [ ] Shuffle in each mode
- [ ] Sort
- [ ] Edit a card
- [ ] Info
- [ ] Reshow
- [ ] Skip
- [ ] Reverse

**Comment by alanxoc3** [comment]
These have all been implemented (well, besides reverse, skip, info, sort, and shuffle, but I don't know if I even want to implement those anymore). Wow, I forgot these issues were here anyway.
